### ISSUE TITLE
TypeError when adding an EthernetControlPopulation after simulation has been started 

### ISSUE THREAD

**Issue by bjuergens** [SpiNNakerManchester/sPyNNaker#1037]
I have yet another problem with Spinnaker-Integration in NRP. I hope you still have some patience left for me :-)

Should it be possible to add or change an EthernetControlPopulation after a simulation has been started? When I try to do this, I get `TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'`

____

Minimum example + workaround

```python
from pyNN import spiNNaker as sim
import os
import tempfile
import threading
import time
import traceback
from enum import Enum
from spynnaker.pyNN.external_devices_models import \
    AbstractMulticastControllableDevice, \
    AbstractEthernetTranslator
from spinn_front_end_common.utilities.globals_variables import get_simulator


class SendType(Enum):
    SEND_TYPE_ACCUM = 2


class MyDevice(AbstractMulticastControllableDevice):
    @property
    def device_control_key(self): return 123

    @property
    def device_control_max_value(self): return 10.0

    @property
    def device_control_min_value(self): return 0.0

    @property
    def device_control_partition_id(self): return "my partition id"

    @property
    def device_control_send_type(self): return SendType.SEND_TYPE_ACCUM

    @property
    def device_control_timesteps_between_sending(self): return 500

    @property
    def device_control_uses_payload(self): return False


class MyAbstractEthernetTranslator(AbstractEthernetTranslator):
    def translate_control_packet(self, multicast_packet): pass


os.chdir(tempfile.mkdtemp())
print(os.getcwd())
sim.setup()

device = MyDevice()
translator = MyAbstractEthernetTranslator()
model = sim.external_devices.ExternalDeviceLifControl([device], False, translator)

runner = threading.Thread(target=sim.external_devices.run_forever)
runner.daemon = True
runner.start()

print("sleeping 50s until brain is loaded")
time.sleep(50)  # it takes about 47s for the brain to load onto the board
try:
    print("trying to add EthernetControlPopulation")
    population = sim.external_devices.EthernetControlPopulation(1, model)
except Exception as e:
    print(e)
    traceback.print_exc()


if get_simulator(). _current_run_timesteps is None:
    print("applying workaround")
    get_simulator(). _current_run_timesteps = 0

print("trying to add EthernetControlPopulation again")
population = sim.external_devices.EthernetControlPopulation(1, model)

print("sleep 2s")
time.sleep(2)
sim.end()

```

relevant error message + stacktrace 

```
Traceback (most recent call last):
  File "/home/bjuergens/Documents/MVE_restart_spinnaker/src/test_tf.py", line 61, in <module>
    population = sim.external_devices.EthernetControlPopulation(1, model)
  File "/home/bjuergens/.opt/platform_venv/local/lib/python2.7/site-packages/spynnaker8/external_devices/__init__.py", line 173, in EthernetControlPopulation
    population = Population(n_neurons, model, label=label)
  File "/home/bjuergens/.opt/platform_venv/local/lib/python2.7/site-packages/spynnaker8/models/populations/population.py", line 70, in __init__
    Recorder.__init__(self, population=self)
  File "/home/bjuergens/.opt/platform_venv/local/lib/python2.7/site-packages/spynnaker8/models/recorder.py", line 50, in __init__
    self._recording_start_time = get_simulator().t
  File "/home/bjuergens/.opt/platform_venv/local/lib/python2.7/site-packages/spynnaker8/spinnaker.py", line 244, in t
    self._current_run_timesteps * (self.machine_time_step / 1000.0))
TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'
```

Note: I do not know if the workaround actually solves anything or if it just makes the error message go away without actually adding a functional EthernetControlPopulation

**Comment by Christian-B** [comment]
The way the system works the only way to add a Population after a simulation has started is to reset the simulation completely.

Change this is totally out of scope especially now that the core development team is being reduced due to the end of various funding projects.
