### ISSUE TITLE
Fake_IF_curr_exp.aplx out of date

### ISSUE THREAD

**Issue by andrewgait** [SpiNNakerManchester/sPyNNaker#1040]
https://github.com/SpiNNakerManchester/sPyNNaker8/blob/master/p8_integration_tests/test_provenance/test_provenance_when_not_finished.py currently fails (RTE), at a guess because the "fake binary" hasn't been rebuilt for some time:

2018-07-09 15:07:03 ERROR: Error when calling spinn_front_end_common.interface.interface_functions.ApplicationRunner.__call__ with inputs ['no_sync_changes', 'send_start_notification', 'txrx', 'send_stop_notification', 'notification_interface', 'buffer_manager', 'app_id', 'time_threshold', 'time_scale_factor', 'wait_on_confirmation', 'executable_targets', 'runtime', 'executable_types']
2018-07-09 15:07:03 ERROR: An error has occurred during simulation
2018-07-09 15:07:03 ERROR: 1 cores have reached an error state CPUState.RUN_TIME_EXCEPTION:
Traceback (most recent call last):
  File "/localhome/mbbssag3/spinnaker/git/SpiNNFrontEndCommon/spinn_front_end_common/interface/abstract_spinnaker_base.py", line 1876, in _do_run
    executor.execute_mapping()
  File "/localhome/mbbssag3/spinnaker/git/PACMAN/pacman/executor/pacman_algorithm_executor.py", line 626, in execute_mapping
    self._execute_mapping()
  File "/localhome/mbbssag3/spinnaker/git/PACMAN/pacman/executor/pacman_algorithm_executor.py", line 642, in _execute_mapping
    results = algorithm.call(self._internal_type_mapping)
  File "/localhome/mbbssag3/spinnaker/git/PACMAN/pacman/executor/algorithm_classes/abstract_python_algorithm.py", line 46, in call
    results = self.call_python(method_inputs)
  File "/localhome/mbbssag3/spinnaker/git/PACMAN/pacman/executor/algorithm_classes/python_class_algorithm.py", line 58, in call_python
    return method(**inputs)
  File "/localhome/mbbssag3/spinnaker/git/SpiNNFrontEndCommon/spinn_front_end_common/interface/interface_functions/application_runner.py", line 62, in __call__
    time_threshold, run_until_complete)
  File "/localhome/mbbssag3/spinnaker/git/SpiNNFrontEndCommon/spinn_front_end_common/interface/interface_functions/application_runner.py", line 98, in run_application
    executable_targets.all_core_subsets, app_id, _GOOD_STATES)
  File "/localhome/mbbssag3/spinnaker/git/SpiNNMan/spinnman/transceiver.py", line 2056, in wait_for_cores_to_be_in_state
    error_cores, cpu_state))
SpinnmanException: 1 cores have reached an error state CPUState.RUN_TIME_EXCEPTION:
2018-07-09 15:07:03 INFO: 

Attempting to extract data

Getting Router Provenance
2018-07-09 15:07:03 ERROR: 0, 0, 3: RUN_TIME_EXCEPTION (SWERR) Fake_IF_curr_ex
2018-07-09 15:07:03 ERROR: r0=0x0000000D r1=0x00000000 r2=0x00004000 r3=0x0000000C
2018-07-09 15:07:03 ERROR: r4=0x00404868 r5=0x00000003 r6=0x00404DA0 r7=0x00000001
2018-07-09 15:07:03 ERROR: PSR=0x600000DF SR=0x0040FB58 LR=0x000015D4
Extracting IOBUF from the machine
2018-07-09 15:07:03 ERROR: 0, 0, 3: There should be no plastic synapses! (synapse_dynamics_static_impl.c:  28)
2018-07-09 15:07:03 ERROR: 0, 0, 3: Error processing spike 0x1 for address 0x603435a4(local=0x408e9c) (spike_processing.c: 230)
2018-07-09 15:07:03 ERROR: 0, 0, 3: 0: 0x20000201 (spike_processing.c: 235)
2018-07-09 15:07:03 ERROR: 0, 0, 3: 1: 0x0 (spike_processing.c: 235)
2018-07-09 15:07:03 ERROR: 0, 0, 3: 2: 0x1 (spike_processing.c: 235)
F

**Comment by andrewgait** [comment]
(Issue transferred from sPyNNaker8 to sPyNNaker)

@alan-stokes was assigned to this; I guess someone else should probably take it over.  From my perspective it could probably be closed but it may be worth checking whether the functionality this was testing is tested elsewhere.

**Comment by dkfellows** [comment]
Appears to be outdated
