### ISSUE TITLE
SpynnakerPoissonControlConnection broken

### ISSUE THREAD

**Issue by andrewgait** [SpiNNakerManchester/sPyNNaker#1053]
The poisson_live_rates(...) test in sPyNNaker/spynnaker_integration_tests/test_spike_source/test_poisson_spike_source.py is broken; errors with both

```
2021-03-31 08:53:35 INFO: Notifying the toolchain that the database has been read
2021-03-31 08:53:35 INFO: Waiting for message to indicate that the simulation has started or resumed
2021-03-31 08:53:35 INFO: ** Confirmation from 127.0.0.1:62950 received, continuing **
2021-03-31 08:53:35 WARNING: *** Failed to receive notification from external application on 127.0.0.1:19999 about the database ***
Traceback (most recent call last):
  File "/Users/andrewgait/work/spinnaker/git/SpiNNMan/spinnman/connections/udp_packet_connections/udp_connection.py", line 154, in receive
    return self._socket.recv(300)
ConnectionRefusedError: [Errno 61] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/andrewgait/work/spinnaker/git/SpiNNFrontEndCommon/spinn_front_end_common/utilities/notification_protocol/notification_protocol.py", line 175, in __do_read_notify
    c.receive_eieio_message()
  File "/Users/andrewgait/work/spinnaker/git/SpiNNMan/spinnman/connections/udp_packet_connections/eieio_connection.py", line 37, in receive_eieio_message
    data = self.receive(timeout)
  File "/Users/andrewgait/work/spinnaker/git/SpiNNMan/spinnman/connections/udp_packet_connections/udp_connection.py", line 158, in receive
    raise SpinnmanIOException(str(e)) from e
```

and

```
2021-03-31 08:53:35 INFO: Waiting for message to indicate that the simulation has stopped or paused
Exception in thread start_resume callback thread for live_event_connection 62950:0.0.0.0:
Traceback (most recent call last):
  File "/Users/andrewgait/work/spinnaker/git/SpiNNMan/spinnman/connections/udp_packet_connections/udp_connection.py", line 207, in send_to
    while not self._socket.sendto(data, address):
TypeError: str, bytes or bytearray expected, not memoryview

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/andrewgait/work/spinnaker/git/sPyNNaker/spynnaker/pyNN/connections/spynnaker_poisson_control_connection.py", line 87, in _start_callback_wrapper
    callback(self.__label(label), connection)
  File "/Users/andrewgait/work/spinnaker/git/sPyNNaker/spynnaker_integration_tests/test_spike_source/test_poisson_spike_source.py", line 193, in set_rates
    conn.set_rates(label, [(i, 50) for i in range(50)])
  File "/Users/andrewgait/work/spinnaker/git/sPyNNaker/spynnaker/pyNN/connections/spynnaker_poisson_control_connection.py", line 147, in set_rates
    self.send_events_with_payloads(control, atom_ids_and_payloads)
  File "/Users/andrewgait/work/spinnaker/git/SpiNNFrontEndCommon/spinn_front_end_common/utilities/connections/live_event_connection.py", line 557, in send_events_with_payloads
    (ip_address, SCP_SCAMP_PORT))
  File "/Users/andrewgait/work/spinnaker/git/SpiNNMan/spinnman/connections/udp_packet_connections/udp_connection.py", line 210, in send_to
    raise SpinnmanIOException(str(e)) from e
spinnman.exceptions.SpinnmanIOException: IO Error: str, bytes or bytearray expected, not memoryview
```

which then means that there are no spikes and so the test fails.

balanced_random_live_rate.py in PyNN8Examples is also not working correctly - it appears to run (though with the above errors), but the plot doesn't look right afterwards.

Could plausibly be related to https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/776 so assigning @dkfellows to see if he has any ideas.

**Comment by dkfellows** [comment]
The immediate problem is that the _address_ used in the communications is (which is pulled out of the DB) was being wrapped as a `memoryview` (there's several options; that one is very good for pulling binary blobs out). “Hilarity” (a strange error message that doesn't say much about what's actually going wrong) ensued. The hard part was realising that it really was the address; that's known to originate from the DB, and is supposed to be a different type in this case; it's an explicit configurable, and the fix is to configure it.
