### ISSUE TITLE
Error using SpiNN Local board

### ISSUE THREAD

**Issue by lungsi** [SpiNNakerManchester/sPyNNaker#1093]
Python: 2.7
sPyNNaker8
```
pip show sPyNNaker8
Name: sPyNNaker8
Version: 1!4.0.0
Summary: Tools for simulating neural models generated using PyNN 0.8 on the SpiNNaker platform
```
Board: SpiNN-3 DMC, ST, Sep11

As per [instructions](http://spinnakermanchester.github.io/spynnaker/4.0.0/PyNNOnSpinnakerInstall.html) I set my wired network settings as

- IP address = 192.168.240.254
- sub-mask = 255.255.255.0
- default gateway = 0.0.0.0

But I noticed that the `machineName = 192.168.240.253` in the [instructions](http://spinnakermanchester.github.io/spynnaker/4.0.0/PyNNOnSpinnakerInstall.html) as well as in the [nengo_spinnaker.conf.example](https://github.com/project-rig/nengo_spinnaker/blob/master/nengo_spinnaker.conf.example) so I set `IP address = 192.168.240.254`.

I then pinged
```
root@6ff47bec99ee:/# ping -w3 192.168.240.253
PING 192.168.240.253 (192.168.240.253) 56(84) bytes of data.
64 bytes from 192.168.240.253: icmp_seq=1 ttl=64 time=0.155 ms
64 bytes from 192.168.240.253: icmp_seq=2 ttl=64 time=0.164 ms
64 bytes from 192.168.240.253: icmp_seq=3 ttl=64 time=0.180 ms

--- 192.168.240.253 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2044ms
rtt min/avg/max/mdev = 0.155/0.166/0.180/0.014 ms
```
Now in my local `.spinnaker.cfg` I set
```
[Machine]
machineName = 192.168.240.253
version = 3
```
and ran the example [`synfire_if_curr_exp.py`](https://github.com/SpiNNakerManchester/PyNN8Examples/archive/4.0.0.zip) but I got **IO Error: Failed to communicate with the machine**
```
>>> sim.run(runtime)
2019-05-21 14:19:25 INFO: Simulating for 5 1000.000000ms timesteps using a hardware timestep of 1000000us
2019-05-21 14:19:25 INFO: Starting execution process
2019-05-21 14:19:25 INFO: Creating transceiver for 192.168.240.253
2019-05-21 14:19:25 INFO: Working out if machine is booted
2019-05-21 14:19:25 ERROR: Error when calling spinn_front_end_common.interface.interface_functions.MachineGenerator.__call__ with inputs {'downed_chips': set([]), 'reset_machine_on_start_up': False, 'hostname': '192.168.240.253', 'scamp_connection_data': None, 'boot_port_num': None, 'bmp_details': None, 'enable_reinjection': True, 'downed_links': set([]), 'max_sdram_size': None, 'downed_cores': set([]), 'auto_detect_bmp': False, 'board_version': 3}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/envs/py27/local/lib/python2.7/site-packages/spynnaker8/__init__.py", line 515, in run
    return __pynn_run(simtime, callbacks=callbacks)
  File "/envs/py27/local/lib/python2.7/site-packages/pyNN/common/control.py", line 110, in run
    return run_until(simulator.state.t + simtime, callbacks)
  File "/envs/py27/local/lib/python2.7/site-packages/pyNN/common/control.py", line 92, in run_until
    simulator.state.run_until(time_point)
  File "/envs/py27/local/lib/python2.7/site-packages/spynnaker8/spinnaker.py", line 128, in run_until
    self._run(tstop - self.t)
  File "/envs/py27/local/lib/python2.7/site-packages/spynnaker8/spinnaker.py", line 175, in _run
    AbstractSpiNNakerCommon.run(self, duration_ms)
  File "/envs/py27/local/lib/python2.7/site-packages/spynnaker/pyNN/abstract_spinnaker_common.py", line 312, in run
    AbstractSpinnakerBase._run(self, run_time)
  File "/envs/py27/local/lib/python2.7/site-packages/spinn_front_end_common/interface/abstract_spinnaker_base.py", line 850, in _run
    self._get_machine(total_run_time, n_machine_time_steps)
  File "/envs/py27/local/lib/python2.7/site-packages/spinn_front_end_common/interface/abstract_spinnaker_base.py", line 1214, in _get_machine
    inputs, algorithms, outputs, "machine_generation")
  File "/envs/py27/local/lib/python2.7/site-packages/spinn_front_end_common/interface/abstract_spinnaker_base.py", line 1105, in _run_algorithms
    executor.execute_mapping()
  File "/envs/py27/local/lib/python2.7/site-packages/pacman/executor/pacman_algorithm_executor.py", line 432, in execute_mapping
    self._execute_mapping()
  File "/envs/py27/local/lib/python2.7/site-packages/pacman/executor/pacman_algorithm_executor.py", line 448, in _execute_mapping
    results = algorithm.call(self._internal_type_mapping)
  File "/envs/py27/local/lib/python2.7/site-packages/pacman/executor/algorithm_classes/abstract_python_algorithm.py", line 44, in call
    results = self.call_python(method_inputs)
  File "/envs/py27/local/lib/python2.7/site-packages/pacman/executor/algorithm_classes/python_class_algorithm.py", line 56, in call_python
    return method(**inputs)
  File "/envs/py27/local/lib/python2.7/site-packages/spinn_front_end_common/interface/interface_functions/machine_generator.py", line 71, in __call__
    enable_reinjector=enable_reinjection)
  File "/envs/py27/local/lib/python2.7/site-packages/spinnman/transceiver.py", line 980, in ensure_board_is_ready
    width, height)
  File "/envs/py27/local/lib/python2.7/site-packages/spinnman/transceiver.py", line 1067, in _try_to_find_scamp_and_boot
    "Failed to communicate with the machine")
spinnman.exceptions.SpinnmanIOException: IO Error: Failed to communicate with the machine
```

I also commented out the above configuration file and did the same thing in `/envs/py27/local/lib/python2.7/site-packages/spinn_front_end_common/interface/spinnaker.cfg` which resulted in a different error *ValueError: invalid literal for int() with base 10: '3#None'*
```
>>> sim.run(runtime)
2019-05-21 15:11:49 INFO: Simulating for 5 1000.000000ms timesteps using a hardware timestep of 1000000us
2019-05-21 15:11:49 INFO: Starting execution process
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/envs/py27-pyNNmoose/local/lib/python2.7/site-packages/spynnaker8/__init__.py", line 515, in run
    return __pynn_run(simtime, callbacks=callbacks)
  File "/envs/py27-pyNNmoose/local/lib/python2.7/site-packages/pyNN/common/control.py", line 110, in run
    return run_until(simulator.state.t + simtime, callbacks)
  File "/envs/py27-pyNNmoose/local/lib/python2.7/site-packages/pyNN/common/control.py", line 92, in run_until
    simulator.state.run_until(time_point)
  File "/envs/py27-pyNNmoose/local/lib/python2.7/site-packages/spynnaker8/spinnaker.py", line 128, in run_until
    self._run(tstop - self.t)
  File "/envs/py27-pyNNmoose/local/lib/python2.7/site-packages/spynnaker8/spinnaker.py", line 175, in _run
    AbstractSpiNNakerCommon.run(self, duration_ms)
  File "/envs/py27-pyNNmoose/local/lib/python2.7/site-packages/spynnaker/pyNN/abstract_spinnaker_common.py", line 312, in run
    AbstractSpinnakerBase._run(self, run_time)
  File "/envs/py27-pyNNmoose/local/lib/python2.7/site-packages/spinn_front_end_common/interface/abstract_spinnaker_base.py", line 850, in _run
    self._get_machine(total_run_time, n_machine_time_steps)
  File "/envs/py27-pyNNmoose/local/lib/python2.7/site-packages/spinn_front_end_common/interface/abstract_spinnaker_base.py", line 1197, in _get_machine
    self._handle_machine_common_config(inputs)
  File "/envs/py27-pyNNmoose/local/lib/python2.7/site-packages/spinn_front_end_common/interface/abstract_spinnaker_base.py", line 1379, in _handle_machine_common_config
    "Machine", "version")
  File "/envs/py27-pyNNmoose/local/lib/python2.7/site-packages/spinn_front_end_common/interface/abstract_spinnaker_base.py", line 2516, in _read_config_int
    return helpful_functions.read_config_int(self._config, section, item)
  File "/envs/py27-pyNNmoose/local/lib/python2.7/site-packages/spinn_front_end_common/utilities/helpful_functions.py", line 398, in read_config_int
    return int(value)
ValueError: invalid literal for int() with base 10: '3#None'
```

* are my `machineName = 192.168.240.253` and `version = 3` values correct for my board **SpiNN-3 DMC, ST, Sep11**?
* could my board be defective?
* why am I getting separate error messages from different configuration file locations for the same parameter values?

**Comment by lplana** [comment]
This is one of the 3 boards that Alan had in Edinburgh.

In case that it helps, I found an old email from Alan asking about the process to change the IP addresses of one of his boards. I'm not sure if it refers to this board though. He wanted the following changes:

> 192.168.240.0 which has mac address  -00-00-a4-f0-00-00 to move to ip address 129.215.63.136 
> 192.168.240.1 which has mac address   -00-00-a4-f0-00-01 to move to ip address  129.215.63.137

**Comment by andrewgait** [comment]
Oh, it's the other one of Alan's old boards (I have the other two), in which case I think the IP address you need to use might be 192.268.2.203 (based on the conversation I had with him when setting up the other two boards here).

Please let us know which IP address works and we'll update our records.

**Comment by Helloworld-Le** [comment]
Thank you both for your swift reply!  Should the 192.268.2.203 be 192.168.2.203?  And after changing the Machine Name to this IP address in my .cfg file? should the network configuration also be changed?

**Comment by Helloworld-Le** [comment]
Thank you for your quick reply! I have tried all of them and none is working. I also tried changing the network configuration. Can you check again the IP (192.268.2.203), should it be 192.168.2.203 or something else? In each case, after changing the machine name to the new IP address in .spynnaker.cfg, how should I modify the network configuration?

**Comment by andrewgait** [comment]
Apologies, yes, the machineName in the config file should be 192.168.2.203.  The network configuration should still be 192.168.240.254, but if that still doesn’t work then try 192.168.2.254 instead.

**Comment by Helloworld-Le** [comment]
I tried 

> Network Address: 192.168.240.254
machineName:     192.168.2.203

> Network Address: 192.168.2.254
machineName:     192.168.2.203

> Network Address: 192.168.240.254
machineName:     192.168.240.203

Sadly, none of them is working. 

My desktop is connected to WiFi and then using a cable connects the Spinn-5 board (I also tried switching between the 2 Ethernet ports on the spinn-5 board, also used different cables).

**Comment by andrewgait** [comment]
I'm afraid I'm not sure what else we can try here.  Can I check again what you have set in your network configuration settings?  It should (I think) be:

IP address: 192.168.2.254
Subnet mask: 255.255.255.0 (It looked like you may have set 255.255.0.0 from your output above?)

and then in the cfg file:

machineName = 192.168.2.203

If this still doesn't work another option I guess is a video call where you share your screen and we try to troubleshoot it.  If you need to do this then let me know (email andrew.gait@manchester.ac.uk) and we can probably arrange something.

**Comment by rowleya** [comment]
From the above, shouldn't the IP address of the board be 129.215.63.137?

In that case, you would need to set your IP address to something in that range e.g. 129.215.63.254, with a subnet mask of 255.255.255.0.

Note that this is an official IP address probably from Edinburgh.  If you are using this with a cable connected only between your computer and the board, this should be fine, but note that it could otherwise interfere with communications, particularly if you ever connect to the Edinburgh network that this was connected to.  I am mainly saying this to trigger a memory of this message in case that ever happens!

**Comment by Helloworld-Le** [comment]
Hi @andrewgait , I certainly tried what you said but it was not working last time. But it is working now! 

I haven't realized what else I changed  but I can confirm this board is now working with:

> MachineName = 192.168.2.203
IP address: 192.168.2.254
Subnet mask: 255.255.255.0 

Also, there is only one Ethernet port working with the above configuration. Is this something that should happen? (I am already happy with having one port working correctly.)

**Comment by andrewgait** [comment]
Hi, glad to hear you have it working!  Only one of the ports should be working if I remember correctly (I think the lower one of the two), the other is for the BMP.
