### ISSUE TITLE
Exception when running PyNN simulation

### ISSUE THREAD

**Issue by ferqui** [SpiNNakerManchester/sPyNNaker#1154]
Hello, I was installing PyNN with SpiNNaker following the guide using a local board. When I was running the va_benchmark.py example, it throws the following error, and I cannot figure out the reason.

```2022-03-11 10:53:22 ERROR: Error when calling spinn_front_end_common.interface.interface_functions.host_no_bitfield_router_compression.pair_compression with inputs dict_keys(['routing_tables', 'transceiver', 'executable_finder', 'machine', 'app_id', 'provenance_file_path', 'compress_as_much_as_possible', 'write_compressor_iobuf'])
Traceback (most recent call last):
  File "va_benchmark.py", line 219, in <module>
    p.run(tstop)
  File "/home/fernando/spinnenv/lib/python3.8/site-packages/spynnaker8/__init__.py", line 703, in run
    return __pynn["run"](simtime, callbacks=callbacks)
  File "/home/fernando/spinnenv/lib/python3.8/site-packages/pyNN/common/control.py", line 111, in run
    return run_until(simulator.state.t + simtime, callbacks)
  File "/home/fernando/spinnenv/lib/python3.8/site-packages/pyNN/common/control.py", line 93, in run_until
    simulator.state.run_until(time_point)
  File "/home/fernando/spinnenv/lib/python3.8/site-packages/spynnaker8/spinnaker.py", line 119, in run_until
    self._run_wait(tstop - self.t)
  File "/home/fernando/spinnenv/lib/python3.8/site-packages/spynnaker8/spinnaker.py", line 150, in _run_wait
    super(SpiNNaker, self).run(duration_ms, sync_time)
  File "/home/fernando/spinnenv/lib/python3.8/site-packages/spynnaker/pyNN/abstract_spinnaker_common.py", line 380, in run
    super().run(run_time, sync_time)
  File "/home/fernando/spinnenv/lib/python3.8/site-packages/spinn_front_end_common/interface/abstract_spinnaker_base.py", line 780, in run
    self._run(run_time, sync_time)
  File "/home/fernando/spinnenv/lib/python3.8/site-packages/spinn_front_end_common/interface/abstract_spinnaker_base.py", line 983, in _run
    self._do_load(graph_changed, data_changed)
  File "/home/fernando/spinnenv/lib/python3.8/site-packages/spinn_front_end_common/interface/abstract_spinnaker_base.py", line 1940, in _do_load
    executor = self._run_algorithms(
  File "/home/fernando/spinnenv/lib/python3.8/site-packages/spinn_front_end_common/interface/abstract_spinnaker_base.py", line 1195, in _run_algorithms
    raise e
  File "/home/fernando/spinnenv/lib/python3.8/site-packages/spinn_front_end_common/interface/abstract_spinnaker_base.py", line 1175, in _run_algorithms
    executor.execute_mapping()
  File "/home/fernando/spinnenv/lib/python3.8/site-packages/pacman/executor/pacman_algorithm_executor.py", line 666, in execute_mapping
    self.__execute_mapping()
  File "/home/fernando/spinnenv/lib/python3.8/site-packages/pacman/executor/pacman_algorithm_executor.py", line 682, in __execute_mapping
    results = algorithm.call(self._internal_type_mapping)
  File "/home/fernando/spinnenv/lib/python3.8/site-packages/pacman/executor/algorithm_classes/abstract_python_algorithm.py", line 77, in call
    results = self.call_python(method_inputs)
  File "/home/fernando/spinnenv/lib/python3.8/site-packages/pacman/executor/algorithm_classes/python_function_algorithm.py", line 80, in call_python
    raise e
  File "/home/fernando/spinnenv/lib/python3.8/site-packages/pacman/executor/algorithm_classes/python_function_algorithm.py", line 75, in call_python
    return function(**inputs)
  File "/home/fernando/spinnenv/lib/python3.8/site-packages/spinn_front_end_common/interface/interface_functions/host_no_bitfield_router_compression.py", line 113, in pair_compression
    compression.compress()
  File "/home/fernando/spinnenv/lib/python3.8/site-packages/spinn_front_end_common/interface/interface_functions/host_no_bitfield_router_compression.py", line 249, in compress
    self._load_routing_table(routing_table)
  File "/home/fernando/spinnenv/lib/python3.8/site-packages/spinn_front_end_common/interface/interface_functions/host_no_bitfield_router_compression.py", line 274, in _load_routing_table
    base_address = self._transceiver.malloc_sdram(
  File "/home/fernando/spinnenv/lib/python3.8/site-packages/spinnman/transceiver.py", line 2373, in malloc_sdram
    process.malloc_sdram(x, y, size, app_id, tag)
  File "/home/fernando/spinnenv/lib/python3.8/site-packages/spinnman/processes/malloc_sdram_process.py", line 51, in malloc_sdram
    self.check_for_error()
  File "/home/fernando/spinnenv/lib/python3.8/site-packages/spinnman/processes/abstract_process.py", line 66, in check_for_error
    raise SpinnmanGenericProcessException(
  File "/home/fernando/spinnenv/lib/python3.8/site-packages/spinnman/connections/scp_request_pipeline.py", line 246, in _single_retrieve
    response.read_bytestring(raw_data, offset)
  File "/home/fernando/spinnenv/lib/python3.8/site-packages/spinnman/messages/scp/abstract_messages/scp_response.py", line 50, in read_bytestring
    self.read_data_bytestring(data, _SCP_DATA_OFFSET + offset)
  File "/home/fernando/spinnenv/lib/python3.8/site-packages/spinnman/messages/scp/impl/sdram_alloc.py", line 97, in read_data_bytestring
    raise SpinnmanInvalidParameterException(
spinnman.exceptions.SpinnmanGenericProcessException: 
     Received exception class: SpinnmanInvalidParameterException 
     With message: Setting parameter SDRAM Allocation response base address to value 0 is invalid: Could not allocate 252 bytes of SDRAM 
     When sending to 2:4:0
     Stack trace: []


These log messages where generated at level WARNING or above
Extra params {'db_name': 'va_benchmark.sqlite', 'threads': 1, 'filename': 'va_CUBA.xml', 'label': 'VA'} have been applied to the setup command which we do not consider
Error when calling spinn_front_end_common.interface.interface_functions.host_no_bitfield_router_compression.pair_compression with inputs dict_keys(['routing_tables', 'transceiver', 'executable_finder', 'machine', 'app_id', 'provenance_file_path', 'compress_as_much_as_possible', 'write_compressor_iobuf'])
```

Do you have any idea what this migh be and how to solve it? Thanks

**Comment by rowleya** [comment]
This is most often a transient issue that might mean either your board simply needs to be reset, or else that the code you are using is not in sync i.e. if you are using git versions of the code, it could mean that after and update you haven't rebuilt the C / Java code (if using Java).
