### ISSUE TITLE
IF_curr_dual_exp implementation broken in several ways

### ISSUE THREAD

**Issue by AlexRast** [SpiNNakerManchester/sPyNNaker#156]
The IF_curr_dual_exp implementation has been broken at least by the time of pushes to master through 23 October. It was not broken in the Arbitrary version current on 24 September. The following problems have occurred:

1) The binary has been renamed to IF_curr_exp_dual.aplx. Same thing with the associated c file etc. Perhaps this was intended, but the python code has not been modified to deal with this. If you ask for an IF_curr_exp_dual neuron type in PyNN the script falls over complaining such a neuron type does not exist.

2) The python implementation is also broken at the DSG stage. You get a message: 

 ======Space unavailable to write all the elements requested by the write operation. Space available: 8; space requested: 12 for region 2.
2015-10-26 16:23:23 ERROR: Error executing data specification for pfc_1 with 400 atoms
Traceback (most recent call last):
  File "./va_network_scaled_IEEE_TNNLS_moving_ref.py", line 687, in <module>
    run(runtime)    # Simulation time
  File "/home/P06/rasta/folders/prg/arbitrary_package/spynnaker/pyNN/__init__.py", line 193, in run
    _spinnaker.run(run_time)
  File "/home/P06/rasta/folders/prg/arbitrary_package/spynnaker/pyNN/spinnaker.py", line 368, in run
    machine=self._machine)
  File "/home/P06/rasta/folders/prg/arbitrary_package/spinn_front_end_common/interface/front_end_common_interface_functions.py", line 311, in execute_data_specification_execution
    runtime_application_data_folder, machine)
  File "/home/P06/rasta/folders/prg/arbitrary_package/spinn_front_end_common/interface/front_end_common_interface_functions.py", line 395, in host_based_data_specification_execution
    raise e
data_specification.exceptions.DataSpecificationNoMoreException

Everything was working in Arbitrary release from 24 September.

**Comment by alan-stokes** [comment]
Howdi alex, 

you are indeed right. 

Ive fixed the python in both the if_duel_exp to point at the right binary, and changed the synapse duel code to state that it actually has 3 syanse types, not the two it thought it had (why we dont just use len on the list, im not sure).

You mentioned to myself directly about the issue that it should indeed be called If_curr_duel_exp instead of If_curr_exp_duel. Ill leave that to rowley to deduce, as a very quick glance at the make files did not come up with a quick fix to do this. It seems theres some naming convention going on that I dont want to risk exploding.

Anyhow, the changes have been applied directly to master. so please repull master and it should all work again.

Alan.
