### ISSUE TITLE
Crash when creating SpikeSourceArray without connections

### ISSUE THREAD

**Issue by cjenzen** [SpiNNakerManchester/sPyNNaker#230]
The following PyNN code crashes with `'NoneType' object has no attribute 'first_key'`

``` python
import pyNN.spiNNaker as p

p.setup(timestep=1)
input = p.Population(1, p.SpikeSourceArray, {})
p.run(100000)
p.end()
```

Backtrace:

```
 Traceback (most recent call last):
  File "test_rec.py", line 12, in <module>
    p.run(100000)
  File "/home/christoph/venvs/spinn2/lib/python2.7/site-packages/spynnaker/pyNN/__init__.py", line 179, in run
    _spinnaker.run(run_time)
  File "/home/christoph/venvs/spinn2/lib/python2.7/site-packages/spynnaker/pyNN/spinnaker.py", line 337, in run
    SpinnakerMainInterface.run(self, run_time)
  File "/home/christoph/venvs/spinn2/lib/python2.7/site-packages/spinn_front_end_common/interface/spinnaker_main_interface.py", line 539, in run
    self._do_data_generation(steps[0])
  File "/home/christoph/venvs/spinn2/lib/python2.7/site-packages/spinn_front_end_common/interface/spinnaker_main_interface.py", line 1051, in _do_data_generation
    executor = self._run_machine_algorithms(inputs, algorithms, [])
  File "/home/christoph/venvs/spinn2/lib/python2.7/site-packages/spinn_front_end_common/interface/spinnaker_main_interface.py", line 647, in _run_machine_algorithms
    executor.execute_mapping()
  File "/home/christoph/venvs/spinn2/lib/python2.7/site-packages/pacman/executor/pacman_algorithm_executor.py", line 445, in execute_mapping
    results = algorithm.call(self._internal_type_mapping)
  File "/home/christoph/venvs/spinn2/lib/python2.7/site-packages/pacman/executor/algorithm_classes/abstract_python_algorithm.py", line 44, in call
    results = self.call_python(method_inputs)
  File "/home/christoph/venvs/spinn2/lib/python2.7/site-packages/pacman/executor/algorithm_classes/python_class_algorithm.py", line 57, in call_python
    return method(**inputs)
  File "/home/christoph/venvs/spinn2/lib/python2.7/site-packages/spynnaker/pyNN/overridden_pacman_functions/spynnaker_data_specification_writer.py", line 41, in __call__
    app_data_runtime_folder)
  File "/home/christoph/venvs/spinn2/lib/python2.7/site-packages/spinn_front_end_common/interface/interface_functions/front_end_common_graph_data_specification_writer.py", line 86, in _generate_data_spec_for_vertices
    associated_vertex.generate_data_specification(spec, placement)
  File "/home/christoph/venvs/spinn2/lib/python2.7/site-packages/spinn_front_end_common/utility_models/reverse_ip_tag_multi_cast_source.py", line 211, in generate_data_specification
    placement.vertex.generate_data_specification(spec, placement)
  File "/home/christoph/venvs/spinn2/lib/python2.7/site-packages/pacman/executor/injection_decorator.py", line 119, in wrapper
    return wrapped_method(obj, *args, **new_args)
  File "/home/christoph/venvs/spinn2/lib/python2.7/site-packages/spinn_front_end_common/utility_models/reverse_ip_tag_multicast_source_machine_vertex.py", line 549, in generate_data_specification
    self._update_virtual_key(routing_info, machine_graph)
  File "/home/christoph/venvs/spinn2/lib/python2.7/site-packages/spinn_front_end_common/utility_models/reverse_ip_tag_multicast_source_machine_vertex.py", line 459, in _update_virtual_key
    self._virtual_key = rinfo.first_key
AttributeError: 'NoneType' object has no attribute 'first_key'
```

Version is the 3.0.0 installed via `pip`.

**Comment by alan-stokes** [comment]
this arises because you have no edges coming from the vertex. It could be checked for, but my question would be:

1. why are you creating a Spike source (whos entire task is to produce a output that is used as input to other neurons) and then not connecting it to anything? this seems a rather peculiar script. 

the github issue tracker should not be used in this way, we recommend posting these kind of issues on the google group "spinnaker users" and if discussion with the community decides this is a bug, it would then move over to the github issue tracker. Therefore I ask that if you feel this needs further action, that you post it there. Given all this, im going to close this issue.

**Comment by astoeckel** [comment]
Alan, thanks for the constructive and quick reply. Please see https://groups.google.com/forum/#!topic/spinnakerusers/Bmx-DaCF9IU for my reply.

**Comment by alan-stokes** [comment]
Having reread your issue. I'm going to reopen both of them. This one is obviously a issue, and I was over zealous with closing it.

**Comment by rowleya** [comment]
A solution to this is:

1. Add a Boolean indicating whether actual packets should be sent from the array (actually ReverseIPTagMulticastSource).

2. If there is no given outgoing key, assume no packets should be sent.

Note that there is an additional issue here that the keys to be sent in the ReverseIPTagMulticastSource can be received dynamically during the simulation (e.g. when it is used as a SpikeInjector).  Nonetheless, we should get an outgoing key if we are going to send spikes, otherwise even injected spikes will go nowhere.  Thus the above solution should work.

**Comment by rowleya** [comment]
In fact, it looks like I have added this problem during the recent refactoring - the ability to not send at all is already available, and simply needs to be reactivated.

**Comment by alan-stokes** [comment]
fixed in master. closing
