### ISSUE TITLE
Not very graceful exit when cores go into RTEs

### ISSUE THREAD

**Issue by pabogdan** [SpiNNakerManchester/sPyNNaker#285]
```bash
2017-03-10 14:01:19 ERROR: 0 cores have gone into an error state:
    1:1:4 in state WATCHDOG

2017-03-10 14:01:19 INFO: 

Attempting to extract data


2017-03-10 14:01:19 ERROR: Error when attempting to recover from error
Traceback (most recent call last):
  File "c:\spinnaker\spinnfrontendcommon\spinn_front_end_common\interface\spinnaker_main_interface.py", line 1287, in _do_run
    self._recover_from_error(e, executor.get_items())
  File "c:\spinnaker\spinnfrontendcommon\spinn_front_end_common\interface\spinnaker_main_interface.py", line 1417, in _recover_from_error
    do_timings=self._do_timings, print_timings=self._print_timings)
  File "c:\spinnaker\pacman\pacman\executor\pacman_algorithm_executor.py", line 129, in __init__
    use_unscanned_annotated_algorithms)
  File "c:\spinnaker\pacman\pacman\executor\pacman_algorithm_executor.py", line 208, in _set_up_pacman_algorithm_listings
    algorithms_names, algorithm_data_objects)
  File "c:\spinnaker\pacman\pacman\executor\pacman_algorithm_executor.py", line 228, in _get_algorithm_data
    "Cannot find algorithm {}".format(algorithm_name))
PacmanConfigurationException: Cannot find algorithm FrontEndCommonIOBufExtractor
Traceback (most recent call last):
  File "C:/SpiNNaker/PyNNExamples/examples/stdp_example.py", line 189, in <module>
    sim.run(simtime)
  File "c:\spinnaker\spynnaker\spynnaker\pyNN\__init__.py", line 221, in run
    _spinnaker.run(run_time)
  File "c:\spinnaker\spynnaker\spynnaker\pyNN\spinnaker.py", line 371, in run
    SpinnakerMainInterface.run(self, run_time)
  File "c:\spinnaker\spinnfrontendcommon\spinn_front_end_common\interface\spinnaker_main_interface.py", line 611, in run
    self._do_run(step)
  File "c:\spinnaker\spinnfrontendcommon\spinn_front_end_common\interface\spinnaker_main_interface.py", line 1298, in _do_run
    extract_iobuf=False)
TypeError: stop() got an unexpected keyword argument 'extract_provenance_data'
```

**Comment by Christian-B** [comment]
Please provider an example script to replicate this behaviour

**Comment by alan-stokes** [comment]
think this is covered with loads of previous fixes. would like peter to verify before closing
