### ISSUE TITLE
SpikeSourceArray getspikes eieio_header error on second spiketime

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/sPyNNaker#328]
Found with:
https://github.com/SpiNNakerManchester/sPyNNaker7/blob/master/p7_integration_tests/test_various/test_bigMultiProcessorSpikeSourcePrint.py

Which I think used to works as I have ranges of expected spikes length.

Stripped down to:
https://github.com/SpiNNakerManchester/sPyNNaker7/blob/master/p7_integration_tests/test_various/spike_record_bug.py

Traceback (most recent call last):
  File "/brenninc/spinnaker/sPyNNaker7/p7_integration_tests/test_various/spike_record_bug.py", line 36, in test_run_
    spikes = do_run(nNeurons)
  File ".../sPyNNaker7/p7_integration_tests/test_various/spike_record_bug.py", line 25, in do_run
    spikes = pop.getSpikes(compatible_output=True)
  File ".../sPyNNaker7/spynnaker7/pyNN/models/pynn_population.py", line 98, in getSpikes
    return self._get_recorded_variable("spikes")
  File ".../sPyNNaker/spynnaker/pyNN/models/recording_common.py", line 183, in _get_recorded_variable
    return self._get_spikes()
  File ".../sPyNNaker/spynnaker/pyNN/models/recording_common.py", line 223, in _get_spikes
    globals_variables.get_simulator().machine_time_step)
  File ".../sPyNNaker/spynnaker/pyNN/models/spike_source/spike_source_array.py", line 191, in get_spikes
    machine_time_step)
  File "./sPyNNaker/spynnaker/pyNN/models/common/eieio_spike_recorder.py", line 67, in get_spikes
    timestamp = eieio_header.payload_base * ms_per_tick
TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'

The second spike time appears not to be getting a full header back from:
eieio_header = EIEIODataHeader.from_bytestring(
                    spike_data, offset)

===
Same in sPyNNaker8
Same with numpy 1.9 and numpy 1.13

**Comment by Christian-B** [comment]
Possibly related to 
https://github.com/SpiNNakerManchester/sPyNNaker7/blob/master/p7_integration_tests/test_various/test_mwh_population_synfire.py
Where the test split over 4 cores produces spikes where the same over core core produces zero spikes.
I thought all p7 test had worked before.

Again same behavior in sPyNNaker8

If not related a new issue will be required.

**Comment by Christian-B** [comment]
This may be the same as https://github.com/SpiNNakerManchester/sPyNNaker/issues/335

**Comment by Christian-B** [comment]
closed as duplicate
