### ISSUE TITLE
On Exception recovery: Chip power monitor gives Bad file descriptor

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/sPyNNaker#372]
Chip Power Monitor fails during stop call after an exception.

Script:
import spynnaker8 as sim
sim.setup(timestep=1)
pop_1 = sim.Population(1, sim.IF_curr_exp, {}, label="pop_1")
sim.run(10)
raise Exception("pop")
sim.stop()
print "Done"

Stack Trace:
Traceback (most recent call last):
  File "C:\Python27\Lib\atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "...\sPyNNaker8\spynnaker8\__init__.py", line 336, in _stop_on_spinnaker
    globals_variables.get_simulator().stop()
  File "...\sPyNNaker\spynnaker\pyNN\abstract_spinnaker_common.py", line 293, in stop
    self, turn_off_machine, clear_routing_tables, clear_tags)
  File "...\SpiNNFrontEndCommon\spinn_front_end_common\interface\abstract_spinnaker_base.py", line 2406, in stop
    self._machine_allocation_controller)
  File "...\SpiNNFrontEndCommon\spinn_front_end_common\utilities\report_functions\energy_report.py", line 119, in __call__
    runtime_total_milliseconds)
  File "...\SpiNNFrontEndCommon\spinn_front_end_common\utilities\report_functions\energy_report.py", line 271, in _write_detailed_report
    runtime_total_milliseconds)
  File "...\SpiNNFrontEndCommon\spinn_front_end_common\utilities\report_functions\energy_report.py", line 504, in _calculate_chips_active_cost
    buffer_manager=buffer_manager)
  File "...\SpiNNFrontEndCommon\spinn_front_end_common\utility_models\chip_power_monitor_machine_vertex.py", line 361, in get_recorded_data
    ChipPowerMonitorMachineVertex.SAMPLE_RECORDING_REGION)
  File "...\SpiNNFrontEndCommon\spinn_front_end_common\interface\buffer_management\buffer_manager.py", line 505, in get_data_for_vertex
    self._transceiver, placement)
  File "...\SpiNNFrontEndCommon\spinn_front_end_common\utility_models\chip_power_monitor_machine_vertex.py", line 302, in get_recording_region_base_address
    RECORDING.value, txrx)
  File "...\SpiNNFrontEndCommon\spinn_front_end_common\utilities\helpful_functions.py", line 50, in locate_memory_region_for_placement
    placement.x, placement.y, placement.p).user[0]
  File "...\SpiNNMan\spinnman\transceiver.py", line 1221, in get_cpu_information_from_core
    return list(self.get_cpu_information(core_subsets))[0]
  File "...\SpiNNMan\spinnman\transceiver.py", line 1117, in get_cpu_information
    cpu_info = process.get_cpu_info(core_subsets)
  File ".\SpiNNMan\spinnman\processes\get_cpu_info_process.py", line 37, in get_cpu_info
    functools.partial(self.handle_response, x, y, p))
  File "...\SpiNNMan\spinnman\processes\abstract_multi_connection_process.py", line 33, in _send_request
    request, callback, error_callback)
  File "...\SpiNNMan\spinnman\connections\scp_request_pipeline.py", line 130, in send_request
    self._connection.send(request_data)
  File "...\SpiNNMan\spinnman\connections\udp_packet_connections\udp_connection.py", line 235, in send
    raise SpinnmanIOException(str(e))
SpinnmanIOException: IO Error: [Errno 9] Bad file descriptor

**Comment by rowleya** [comment]
This seems to be caused by the exit function - such a function doesn't exist in pyNN 0.7.  This is handled differently by sPyNNaker by managing the exception instead.

Fix in SpiNNakerManchester/sPyNNaker8#47

**Comment by Christian-B** [comment]
fixed by removing call to stop after exception handling already did shutdown
