### ISSUE TITLE
Error when running va_benchmark.py in latest pre release

### ISSUE THREAD

**Issue by svadams** [SpiNNakerManchester/sPyNNaker#40]
The errors are as follows:
Traceback (most recent call last):
  File "va_benchmark.py", line 182, in <module>
    run(tstop)
  File "/usr/local/lib/python2.7/dist-packages/spynnaker/pyNN/__init__.py", line 183, in run
    _spinnaker.run(run_time)
  File "/usr/local/lib/python2.7/dist-packages/spynnaker/pyNN/spinnaker.py", line 188, in run
    self.map_model()
  File "/usr/local/lib/python2.7/dist-packages/spynnaker/pyNN/spinnaker.py", line 391, in map_model
    self._execute_router(pacman_report_state)
  File "/usr/local/lib/python2.7/dist-packages/spynnaker/pyNN/spinnaker.py", line 496, in _execute_router
    routing_info=self._routing_infos, machine=self._machine)
  File "/usr/local/lib/python2.7/dist-packages/pacman/utilities/reports.py", line 30, in router_reports
    router_report_from_router_tables(report_folder, routing_tables)
  File "/usr/local/lib/python2.7/dist-packages/pacman/utilities/reports.py", line 316, in router_report_from_router_tables
    hex_key = _uint_32_to_hex_string(key)
  File "/usr/local/lib/python2.7/dist-packages/pacman/utilities/reports.py", line 439, in _uint_32_to_hex_string
    hex_string = "{:x}{:x}".format(top, bottom)
ValueError: Unknown format code 'x' for object of type 'str'

**Comment by rowleya** [comment]
I have made some changes to PACMAN that will hopefully address this issue.  This can be installed as follows:

1.      Update to the latest sPyNNaker pre-release:

pip uninstall sPyNNaker

pip install sPyNNaker --pre

2.      Update to the lastest PACMAN pre-release:

pip uninstall SpiNNaker-PACMAN

pip install SpiNNaker-PACMAN --pre

Note that you will also need to update the External Devices module if you are using it:
pip uninstall sPyNNakerExternalDevicesPlugin
pip install sPyNNakerExternalDevicesPlugin --pre

Let us know if this helps...

**Comment by alan-stokes** [comment]
Im persuming the length of time this has been hanging, and the fact that I think sam's issue ahth gone away, im closing this issue. please feel tree to reopen it if this is not the case.
