### ISSUE TITLE
RNG error with FixedTotalNumberConnector 

### ISSUE THREAD

**Issue by apdavison** [SpiNNakerManchester/sPyNNaker#453]
This line:

https://github.com/SpiNNakerManchester/sPyNNaker/blob/master/spynnaker/pyNN/models/neural_projections/connectors/multapse_connector.py#L68

calls the PyNN RNG object with a distribution name 'multinomial' and parameters in the form of a list. As of PyNN 0.8, the RNGs support only a limited number of distributions with standardized names, and 'multinomial' is not in that list.

I have created PyNN ticket https://github.com/NeuralEnsemble/PyNN/issues/555 to address the PyNN side of this, but you will need to change the parameters to a dictionary (keys `n` and `pvals`) instead of a list.

(Unfortunately, the parameters still need to be a list for PyNN 0.7)

```
Traceback (most recent call last):
  File "tmp/example.py", line 55, in <module>
    net.simulate()
  File "/tmp/job2972132055770751070.tmp/tmp/network.py", line 391, in simulate
    self.sim.run(self.sim_dict['t_sim'])
  File "/opt/git/sPyNNaker8/spynnaker8/__init__.py", line 515, in run
    return __pynn_run(simtime, callbacks=callbacks)
  File "/usr/local/lib/python2.7/dist-packages/pyNN/common/control.py", line 110, in run
    return run_until(simulator.state.t + simtime, callbacks)
  File "/usr/local/lib/python2.7/dist-packages/pyNN/common/control.py", line 92, in run_until
    simulator.state.run_until(time_point)
  File "/opt/git/sPyNNaker8/spynnaker8/spinnaker.py", line 128, in run_until
    self._run(tstop - self.t)
  File "/opt/git/sPyNNaker8/spynnaker8/spinnaker.py", line 175, in _run
    AbstractSpiNNakerCommon.run(self, duration_ms)
  File "/opt/git/sPyNNaker/spynnaker/pyNN/abstract_spinnaker_common.py", line 312, in run
    AbstractSpinnakerBase._run(self, run_time)
  File "/opt/git/SpiNNFrontEndCommon/spinn_front_end_common/interface/abstract_spinnaker_base.py", line 850, in _run
    self._get_machine(total_run_time, n_machine_time_steps)
  File "/opt/git/SpiNNFrontEndCommon/spinn_front_end_common/interface/abstract_spinnaker_base.py", line 1342, in _get_machine
    inputs, algorithms, outputs, "machine_generation")
  File "/opt/git/SpiNNFrontEndCommon/spinn_front_end_common/interface/abstract_spinnaker_base.py", line 1105, in _run_algorithms
    executor.execute_mapping()
  File "/opt/git/PACMAN/pacman/executor/pacman_algorithm_executor.py", line 432, in execute_mapping
    self._execute_mapping()
  File "/opt/git/PACMAN/pacman/executor/pacman_algorithm_executor.py", line 448, in _execute_mapping
    results = algorithm.call(self._internal_type_mapping)
  File "/opt/git/PACMAN/pacman/executor/algorithm_classes/abstract_python_algorithm.py", line 44, in call
    results = self.call_python(method_inputs)
  File "/opt/git/PACMAN/pacman/executor/algorithm_classes/python_class_algorithm.py", line 56, in call_python
    return method(**inputs)
  File "/opt/git/PACMAN/pacman/operations/partition_algorithms/partition_and_place_partitioner.py", line 86, in __call__
    graph, progress_bar, vertex_groups)
  File "/opt/git/PACMAN/pacman/operations/partition_algorithms/partition_and_place_partitioner.py", line 139, in _partition_vertex
    machine_graph, graph, graph_mapper, resource_tracker, progress)
  File "/opt/git/PACMAN/pacman/operations/partition_algorithms/partition_and_place_partitioner.py", line 181, in _partition_by_atoms
    max_atoms_per_core, graph)
  File "/opt/git/PACMAN/pacman/operations/partition_algorithms/partition_and_place_partitioner.py", line 284, in _scale_down_resources
    used_resources = vertex.get_resources_used_by_atoms(vertex_slice)
  File "/opt/git/PACMAN/pacman/executor/injection_decorator.py", line 119, in wrapper
    return wrapped_method(obj, *args, **new_args)
  File "/opt/git/sPyNNaker/spynnaker/pyNN/models/neuron/abstract_population_vertex.py", line 227, in get_resources_used_by_atoms
    vertex_slice, graph, machine_time_step)),
  File "/opt/git/sPyNNaker/spynnaker/pyNN/models/neuron/abstract_population_vertex.py", line 356, in get_sdram_usage_for_atoms
    common_constants.SARK_PER_MALLOC_SDRAM_USAGE) +
  File "/opt/git/sPyNNaker/spynnaker/pyNN/models/neuron/synaptic_manager.py", line 284, in get_sdram_usage_in_bytes
    vertex_slice, in_edges, machine_time_step) +
  File "/opt/git/sPyNNaker/spynnaker/pyNN/models/neuron/synaptic_manager.py", line 246, in _get_estimate_synaptic_blocks_size
    in_edge.n_delay_stages, machine_time_step)
  File "/opt/git/sPyNNaker/spynnaker/pyNN/models/neuron/synaptic_manager.py", line 262, in _get_size_of_synapse_information
    machine_time_step)
  File "/opt/git/sPyNNaker/spynnaker/pyNN/models/neuron/synapse_io/synapse_io_row_based.py", line 54, in get_sdram_usage_in_bytes
    0, max_delay_supported)
  File "/opt/git/sPyNNaker/spynnaker/pyNN/models/neural_projections/connectors/multapse_connector.py", line 91, in get_n_connections_from_pre_vertex_maximum
    self._update_synapses_per_post_vertex(pre_slices, post_slices)
  File "/opt/git/sPyNNaker/spynnaker/pyNN/models/neural_projections/connectors/multapse_connector.py", line 70, in _update_synapses_per_post_vertex
    self._num_synapses, prob_connect])
  File "/usr/local/lib/python2.7/dist-packages/pyNN/random.py", line 124, in next
    rarr = self._next(distribution, n, parameters)
  File "/usr/local/lib/python2.7/dist-packages/pyNN/random.py", line 201, in _next
    distribution_np, parameter_map = self.translations[distribution]
KeyError: 'multinomial'
```

**Comment by andrewgait** [comment]
Will look at this along with https://github.com/SpiNNakerManchester/sPyNNaker8/issues/99 in January.

**Comment by andrewgait** [comment]
It seems like we are still waiting for the PyNN side of this fix, so tagging appropriately.

**Comment by andrewgait** [comment]
It doesn't look like any fix on the PyNN side has been applied yet so leaving this open.
