### ISSUE TITLE
Changing i_offset after first run causes an error in numpy

### ISSUE THREAD

**Issue by mmikaitis** [SpiNNakerManchester/sPyNNaker#556]
This might be a bug, but I do not rule out some issues with my development setup as I was having some pain updating everything these past days. I have everything up to date on macOS. I run a simple script that runs for 60ms, then change the i_offset and run again. But upon changing the parameter there is an error:

2018-10-17 15:54:23 ERROR: Shutdown on exception
Traceback (most recent call last):
  File "test_lif.py", line 53, in <module>
    populations[0].set(i_offset=4.775)
  File "/Users/mantasmikaitis/SpiNNaker/sPyNNaker8/spynnaker8/models/populations/population.py", line 317, in set
    super(Population, self).set(parameter, value)
  File "/Users/mantasmikaitis/SpiNNaker/sPyNNaker/spynnaker/pyNN/models/pynn_population_common.py", line 371, in set
    self._set_check(parameter, value)
  File "/Users/mantasmikaitis/SpiNNaker/sPyNNaker/spynnaker/pyNN/models/pynn_population_common.py", line 354, in _set_check
    self._read_parameters_before_set()
  File "/Users/mantasmikaitis/SpiNNaker/sPyNNaker/spynnaker/pyNN/models/pynn_population_common.py", line 437, in _read_parameters_before_set
    machine_vertex))
  File "/Users/mantasmikaitis/SpiNNaker/sPyNNaker/spynnaker/pyNN/models/neuron/abstract_population_vertex.py", line 714, in read_parameters_from_machine
    self._state_variables)
  File "/Users/mantasmikaitis/SpiNNaker/sPyNNaker/spynnaker/pyNN/models/neuron/implementations/neuron_impl_standard.py", line 143, in read_data
    data, offset, vertex_slice, parameters, state_variables)
  File "/Users/mantasmikaitis/SpiNNaker/sPyNNaker/spynnaker/pyNN/models/neuron/implementations/abstract_standard_neuron_component.py", line 137, in read_data
    values = self.struct.read_data(data, offset, vertex_slice.n_atoms)
  File "/Users/mantasmikaitis/SpiNNaker/sPyNNaker/spynnaker/pyNN/models/neuron/implementations/struct.py", line 110, in read_data
    data, offset=offset, dtype=self.numpy_dtype, count=array_size)
ValueError: itemsize cannot be zero in type

Same issue appears when I run the intergration test from sPyNNaker8, which is very similar to my script: /sPyNNaker8/p8_integration_tests/test_change_neuron_parameters_between_runs/test_set_toffset.py.

**Comment by andrewgait** [comment]
Confirmed as a bug from running integration test, will look at it.

**Comment by mmikaitis** [comment]
Thanks. Is there any work around until you fix this? What I want to do is simply inject i_offset at 60ms and leave it until the end of the simulation. From 0ms to 60ms it needs to be zero.

**Comment by mmikaitis** [comment]
Andrew, thanks for the fix!

There is now a following issue, only with the Izhikevich neuron (not captured by that intergration test because it uses the LIF model):

2018-10-17 18:39:22 ERROR: Shutdown on exception
Traceback (most recent call last):
  File "test_lif.py", line 53, in <module>
    populations[0].set(i_offset=4.775)
  File "/Users/mantasmikaitis/SpiNNaker/sPyNNaker8/spynnaker8/models/populations/population.py", line 317, in set
    super(Population, self).set(parameter, value)
  File "/Users/mantasmikaitis/SpiNNaker/sPyNNaker/spynnaker/pyNN/models/pynn_population_common.py", line 371, in set
    self._set_check(parameter, value)
  File "/Users/mantasmikaitis/SpiNNaker/sPyNNaker/spynnaker/pyNN/models/pynn_population_common.py", line 354, in _set_check
    self._read_parameters_before_set()
  File "/Users/mantasmikaitis/SpiNNaker/sPyNNaker/spynnaker/pyNN/models/pynn_population_common.py", line 437, in _read_parameters_before_set
    machine_vertex))
  File "/Users/mantasmikaitis/SpiNNaker/sPyNNaker/spynnaker/pyNN/models/neuron/abstract_population_vertex.py", line 714, in read_parameters_from_machine
    self._state_variables)
  File "/Users/mantasmikaitis/SpiNNaker/sPyNNaker/spynnaker/pyNN/models/neuron/implementations/neuron_impl_standard.py", line 143, in read_data
    data, offset, vertex_slice, parameters, state_variables)
  File "/Users/mantasmikaitis/SpiNNaker/sPyNNaker/spynnaker/pyNN/models/neuron/neuron_models/abstract_neuron_model.py", line 71, in read_data
    data, offset, vertex_slice, parameters, state_variables)
  File "/Users/mantasmikaitis/SpiNNaker/sPyNNaker/spynnaker/pyNN/models/neuron/implementations/abstract_standard_neuron_component.py", line 142, in read_data
    self.update_values(values, params, variables)
  File "/Users/mantasmikaitis/SpiNNaker/sPyNNaker/spynnaker/pyNN/models/neuron/neuron_models/neuron_model_izh.py", line 98, in update_values
    _a, _b, _c, _d, v, u, _i_offset = values
ValueError: too many values to unpack

**Comment by andrewgait** [comment]
Izhikevich bug should be fixed by https://github.com/SpiNNakerManchester/sPyNNaker/pull/558 (I have also added an Izhikevich run-set-run integration test at https://github.com/SpiNNakerManchester/sPyNNaker8/pull/178).

**Comment by mmikaitis** [comment]
It works. Many thanks!

**Comment by andrewgait** [comment]
I think so - I had a brief look around other neuron components to check for any similar problems, but I didn’t find any.  We can always open new issues if necessary.
