### ISSUE TITLE
Distence_dependence_test fails due to some import issue

### ISSUE THREAD

**Issue by alan-stokes** [SpiNNakerManchester/sPyNNaker#56]
Howdi all. 

The test Distence_dependence_test inside spynnaker-intergrationtests-from_list_type_intergrartion_tests-Distence_dependence_test

fails with this errror

Traceback (most recent call last):
  File "/home/S06/stokesa6/spinniker/alpha_package_103_git/sPyNNaker/integration_tests/from_list_type_integration_tests/Distance_Dependence_Test.py", line 103, in <module>
    target='inhibitory')
  File "/home/S06/stokesa6/spinniker/alpha_package_103_git/sPyNNaker/spynnaker/pyNN/__init__.py", line 304, in Projection
    target, synapse_dynamics, label, rng)
  File "/home/S06/stokesa6/spinniker/alpha_package_103_git/sPyNNaker/spynnaker/pyNN/spinnaker.py", line 919, in create_projection
    timescale_factor=self._time_scale_factor)
  File "/home/S06/stokesa6/spinniker/alpha_package_103_git/sPyNNaker/spynnaker/pyNN/models/pynn_projection.py", line 83, in __init__
    postsynaptic_population._get_vertex.weight_scale, synapse_type)
  File "/home/S06/stokesa6/spinniker/alpha_package_103_git/sPyNNaker/spynnaker/pyNN/models/neural_projections/connectors/distance_dependent_probability_connector.py", line 131, in generate_synapse_list
    d_expression=self.d_expression, distances=distances)
  File "/home/S06/stokesa6/spinniker/alpha_package_103_git/sPyNNaker/spynnaker/pyNN/models/neural_projections/connectors/distance_dependent_probability_connector.py", line 102, in _dd_is_there_a_connection
    d_expression=d_expression, distances=distances)
  File "/usr/lib/python2.7/dist-packages/numpy/core/numeric.py", line 1808, in fromfunction
    return function(*args,**kwargs)
  File "/home/S06/stokesa6/spinniker/alpha_package_103_git/sPyNNaker/spynnaker/pyNN/models/neural_projections/connectors/distance_dependent_probability_connector.py", line 84, in _distance_dependence
    DD[pt] = dist_f(distances[pt])
  File "<string>", line 1, in <lambda>
NameError: global name 'math' is not defined

Alex, as its your test code, can you please fix. 

regards
Alan

**Comment by alan-stokes** [comment]
this doesnt occur in master, so closing issue.
