### ISSUE TITLE
Delay extension incorrectly writing data to region

### ISSUE THREAD

**Issue by such-a-git** [SpiNNakerManchester/sPyNNaker#573]
For unknown reasons my code errors out with the report below. When writing the text specs and tracking the issue, it was found to be a delay extension causing the issue. The written elements are [10.11.218.81_dataSpec_1_2_8.txt](https://github.com/SpiNNakerManchester/sPyNNaker/files/2649816/10.11.218.81_dataSpec_1_2_8.txt)

No idea whats going on, the rest of the code works on sands so must be something to do with a new branch as that is the only difference (sands is behind master by a little while).

Executing data specifications and loading data
|0%                          50%                         100%|
 2018-12-05 17:08:58 ERROR: Error executing data specification for 1, 2, 8
============================================================
2018-12-05 17:08:58 ERROR: Error when calling spinn_front_end_common.interface.interface_functions.HostExecuteDataSpecification.__call__ with inputs ['machine', 'transceiver', 'processor_to_app_data_base_address', 'app_id', 'dsg_targets']
2018-12-05 17:08:58 INFO: Turning off machine
Traceback (most recent call last):
  File "/home/adampcloth/PycharmProjects/motif/methods/agents.py", line 836, in bandit_test
    p.run(runtime)
  File "/home/adampcloth/PycharmProjects/sPyNNaker8/spynnaker8/__init__.py", line 618, in run
    return __pynn["run"](simtime, callbacks=callbacks)
  File "/usr/local/lib/python2.7/dist-packages/pyNN/common/control.py", line 111, in run
    return run_until(simulator.state.t + simtime, callbacks)
  File "/usr/local/lib/python2.7/dist-packages/pyNN/common/control.py", line 93, in run_until
    simulator.state.run_until(time_point)
  File "/home/adampcloth/PycharmProjects/sPyNNaker8/spynnaker8/spinnaker.py", line 123, in run_until
    self._run_wait(tstop - self.t)
  File "/home/adampcloth/PycharmProjects/sPyNNaker8/spynnaker8/spinnaker.py", line 166, in _run_wait
    super(SpiNNaker, self).run(duration_ms)
  File "/home/adampcloth/PycharmProjects/sPyNNaker/spynnaker/pyNN/abstract_spinnaker_common.py", line 317, in run

    super(AbstractSpiNNakerCommon, self).run(run_time)
  File "/home/adampcloth/PycharmProjects/SpiNNFrontEndCommon/spinn_front_end_common/interface/abstract_spinnaker_base.py", line 815, in run
    self._run(run_time)
  File "/home/adampcloth/PycharmProjects/SpiNNFrontEndCommon/spinn_front_end_common/interface/abstract_spinnaker_base.py", line 995, in _run
    self._do_load(application_graph_changed)
  File "/home/adampcloth/PycharmProjects/SpiNNFrontEndCommon/spinn_front_end_common/interface/abstract_spinnaker_base.py", line 1853, in _do_load
    optional_algorithms)
  File "/home/adampcloth/PycharmProjects/SpiNNFrontEndCommon/spinn_front_end_common/interface/abstract_spinnaker_base.py", line 1209, in _run_algorithms
    reraise(*exc_info)
  File "/home/adampcloth/PycharmProjects/SpiNNFrontEndCommon/spinn_front_end_common/interface/abstract_spinnaker_base.py", line 1194, in _run_algorithms
    executor.execute_mapping()
  File "/home/adampcloth/PycharmProjects/PACMAN/pacman/executor/pacman_algorithm_executor.py", line 623, in execute_mapping
    self._execute_mapping()
  File "/home/adampcloth/PycharmProjects/PACMAN/pacman/executor/pacman_algorithm_executor.py", line 639, in _execute_mapping
    results = algorithm.call(self._internal_type_mapping)
  File "/home/adampcloth/PycharmProjects/PACMAN/pacman/executor/algorithm_classes/abstract_python_algorithm.py", line 45, in call
    results = self.call_python(method_inputs)
  File "/home/adampcloth/PycharmProjects/PACMAN/pacman/executor/algorithm_classes/python_class_algorithm.py", line 56, in call_python
    return method(**inputs)
  File "/home/adampcloth/PycharmProjects/SpiNNFrontEndCommon/spinn_front_end_common/interface/interface_functions/host_execute_data_specification.py", line 48, in __call__
    transceiver, machine, app_id, x, y, p, data_spec_file_path)
  File "/home/adampcloth/PycharmProjects/SpiNNFrontEndCommon/spinn_front_end_common/interface/interface_functions/host_execute_data_specification.py", line 71, in _execute
    executor.execute()
  File "/home/adampcloth/PycharmProjects/DataSpecification/data_specification/data_specification_executor.py", line 83, in execute
    if operation_fn(cmd) == END_SPEC_EXECUTOR:
  File "/home/adampcloth/PycharmProjects/DataSpecification/data_specification/data_specification_executor_functions.py", line 202, in execute_write_array
    self._write_bytes_to_mem(value_encoded, "WRITE_ARRAY")
  File "/home/adampcloth/PycharmProjects/DataSpecification/data_specification/data_specification_executor_functions.py", line 358, in _write_bytes_to_mem
    self.__write_blob(data)
  File "/home/adampcloth/PycharmProjects/DataSpecification/data_specification/data_specification_executor_functions.py", line 373, in __write_blob
    region.remaining_space, len(data), self.current_region)
NoMoreException: Space unavailable to write all the elements requested by the write operation. Space available: 0; space requested: 4 for region 1.

**Comment by such-a-git** [comment]
I've switched to master and run with the pulled version and that seems to fix it. Weirdly though now I go back to my other branch that seems to work too. 

Don't exactly know whats happened but it seems to have fixed the issue.

If the bug crops up again I'll let you know. 

Thanks for the help.
