### ISSUE TITLE
Import loop

### ISSUE THREAD

**Issue by dkfellows** [SpiNNakerManchester/sPyNNaker#661]
Observed while looking at [the logs of a documentation build](https://travis-ci.org/SpiNNakerManchester/sPyNNaker/jobs/541158339):

`DelayExtensionVertex` has an import loop with `spynnaker/pyNN/models/neuron/__init__.py`, `spynnaker/pyNN/models/neuron/abstract_population_vertex.py`, and `spynnaker/pyNN/models/neuron/synaptic_manager.py`…

```
/home/travis/build/SpiNNakerManchester/sPyNNaker/doc/source/spynnaker.pyNN.rst:23: WARNING: autodoc: failed to import module u'spynnaker.pyNN.abstract_spinnaker_common'; the following exception was raised:
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 551, in import_object
    __import__(self.modname)
  File "/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/sPyNNaker-1!4.0.1-py2.7.egg/spynnaker/pyNN/abstract_spinnaker_common.py", line 13, in <module>
    from spynnaker.pyNN.models.utility_models import synapse_expander
  File "/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/sPyNNaker-1!4.0.1-py2.7.egg/spynnaker/pyNN/models/utility_models/__init__.py", line 3, in <module>
    from .delay_extension_vertex import DelayExtensionVertex
  File "/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/sPyNNaker-1!4.0.1-py2.7.egg/spynnaker/pyNN/models/utility_models/delay_extension_vertex.py", line 31, in <module>
    from spynnaker.pyNN.models.neuron.synapse_dynamics import (
  File "/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/sPyNNaker-1!4.0.1-py2.7.egg/spynnaker/pyNN/models/neuron/__init__.py", line 1, in <module>
    from .abstract_population_vertex import AbstractPopulationVertex
  File "/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/sPyNNaker-1!4.0.1-py2.7.egg/spynnaker/pyNN/models/neuron/abstract_population_vertex.py", line 24, in <module>
    from .synaptic_manager import SynapticManager
  File "/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/sPyNNaker-1!4.0.1-py2.7.egg/spynnaker/pyNN/models/neuron/synaptic_manager.py", line 30, in <module>
    from spynnaker.pyNN.models.utility_models import DelayExtensionVertex
ImportError: cannot import name DelayExtensionVertex
```

For some reason, it doesn't trigger in normal use.

**Comment by andrewgait** [comment]
Well this is weird: 

`File "/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/sPyNNaker-1!4.0.1-py2.7.egg/spynnaker/pyNN/models/utility_models/delay_extension_vertex.py", line 31, in <module>
    from spynnaker.pyNN.models.neuron.synapse_dynamics import (
  File "/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/sPyNNaker-1!4.0.1-py2.7.egg/spynnaker/pyNN/models/neuron/__init__.py", line 1, in <module>
    from .abstract_population_vertex import AbstractPopulationVertex`

Why is an import from `neuron.synapse_dynamics` going into `neuron/__init__.py`?

**Comment by andrewgait** [comment]
In addition to the above, there's also a problem when importing master_pop_table_generators (again, only found through a documentation build):

> WARNING: /localhome/mbbssag3/spinnaker/git/sPyNNaker/doc/source/spynnaker.pyNN.external_devices_models.rst:17: (WARNING/2) autodoc: failed to import module u'spynnaker.pyNN.external_devices_models.abstract_ethernet_controller'; the following exception was raised:
> Traceback (most recent call last):
>   File "/localhome/mbbssag3/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 657, in import_object
>     __import__(self.modname)
>   File "/localhome/mbbssag3/spinnaker/git/sPyNNaker/spynnaker/pyNN/external_devices_models/__init__.py", line 22, in <module>
>     from .external_device_lif_control import ExternalDeviceLifControl
>   File "/localhome/mbbssag3/spinnaker/git/sPyNNaker/spynnaker/pyNN/external_devices_models/external_device_lif_control.py", line 19, in <module>
>     from spynnaker.pyNN.models.neuron import AbstractPyNNNeuronModelStandard
>   File "/localhome/mbbssag3/spinnaker/git/sPyNNaker/spynnaker/pyNN/models/neuron/__init__.py", line 16, in <module>
>     from .abstract_population_vertex import AbstractPopulationVertex
>   File "/localhome/mbbssag3/spinnaker/git/sPyNNaker/spynnaker/pyNN/models/neuron/abstract_population_vertex.py", line 40, in <module>
>     from .synaptic_manager import SynapticManager
>   File "/localhome/mbbssag3/spinnaker/git/sPyNNaker/spynnaker/pyNN/models/neuron/synaptic_manager.py", line 35, in <module>
>     from spynnaker.pyNN.models.neuron import master_pop_table_generators
> ImportError: cannot import name master_pop_table_generators

(This happens for basically most of the imports in sPyNNaker...)

**Comment by andrewgait** [comment]
This was fixed in the recent merges.
