### ISSUE TITLE
error on fresh installation: TypeError: can't multiply sequence by non-int of type 'float' 

### ISSUE THREAD

**Issue by bjuergens** [SpiNNakerManchester/sPyNNaker#758]
currently the pip installation of spynnaker8 installs a broken package, i think

#### reproduction

```bash
docker run -it ubuntu:18.04 bash
export MPLBACKEND=agg
apt-get update && apt-get install -y python-pip
pip install matplotlib
pip install sPyNNaker8
python -m spynnaker8.setup_pynn
python -c "import pyNN.spiNNaker as sim; sim.setup(); sim.end()"
python -c "import pyNN.spiNNaker as sim; sim.setup(); sim.end()"
```

the last line is duplicated, because on the first run, it sets up the config file, and in the 2nd run it actually starts the initiation. The error also happens, if  ~/.spynnaker.cfg has valid values. 

#### stacktrace / output of last line: 

```
root@50e4e970e93c:/# python -c "import pyNN.spiNNaker as sim; sim.setup(); sim.end()"
Detected PyNN version 0.9.5 and Neo version 0.6.1
['/usr/local/lib/python2.7/dist-packages/spinn_front_end_common/interface/spinnaker.cfg', '/usr/local/lib/python2.7/dist-packages/spynnaker/pyNN/spynnaker.cfg', '/root/.spynnaker.cfg']
2019-12-19 12:32:35 INFO: Read cfg files: /usr/local/lib/python2.7/dist-packages/spinn_front_end_common/interface/spinnaker.cfg, /usr/local/lib/python2.7/dist-packages/spynnaker/pyNN/spynnaker.cfg, /root/.spynnaker.cfg
2019-12-19 12:32:35 INFO: Will search these locations for binaries: /usr/local/lib/python2.7/dist-packages/spinn_front_end_common/common_model_binaries : /usr/local/lib/python2.7/dist-packages/spynnaker/pyNN/model_binaries
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/spynnaker8/__init__.py", line 358, in setup
    n_boards_required=n_boards_required)
  File "/usr/local/lib/python2.7/dist-packages/spynnaker8/spinnaker.py", line 113, in __init__
    front_end_versions=front_end_versions)
  File "/usr/local/lib/python2.7/dist-packages/spynnaker/pyNN/abstract_spinnaker_common.py", line 151, in __init__
    timestep, min_delay, max_delay, self.config, time_scale_factor)
  File "/usr/local/lib/python2.7/dist-packages/spynnaker/pyNN/abstract_spinnaker_common.py", line 194, in _set_up_timings
    if (max_delay is not None and max_delay * 1000.0 >
TypeError: can't multiply sequence by non-int of type 'float'
```

**Comment by rowleya** [comment]
This is a known error due to breaking changes in PyNN 0.9.5 from PyNN 0.9.4; we have mentioned this in the install instructions here:
http://spinnakermanchester.github.io/common_pages/5.0.0/PythonInstall.html

You can solve this by running:
```
pip install pyNN==0.9.4
```

Note that this is fixed in the master code as well.
