### ISSUE TITLE
Errors when running large network

### ISSUE THREAD

**Issue by svadams** [SpiNNakerManchester/sPyNNaker#76]
I just tried to run a network with ~ 98K neurons but got two different errors on two tries. The first time it got past loading but didn't start running and gave this error:

2015-05-15 12:30:36 INFO: *** Awaiting for a response from an external source to state its ready for the simulation to start ***
2015-05-15 12:30:36 INFO: Starting application
2015-05-15 12:30:36 INFO: Checking that the application has started
Traceback (most recent call last):
  File "va_network_scaled_AER.py", line 531, in <module>
    Frontend.run(runtime)    # Simulation time
  File "/usr/local/lib/python2.7/dist-packages/spynnaker/pyNN/__init__.py", line 188, in run
    _spinnaker.run(run_time)
  File "/usr/local/lib/python2.7/dist-packages/spynnaker/pyNN/spinnaker.py", line 390, in run
    self._start_all_cores(executable_targets, self._app_id)
  File "/usr/local/lib/python2.7/dist-packages/spinn_front_end_common/interface/front_end_common_interface_functions.py", line 302, in _start_all_cores
    .format(processors_running, total_processors, break_down))
spinn_front_end_common.utilities.exceptions.ExecutableFailedToStartException: Only 331 of 402 processors started with breakdown 
1:2:1 successfully in state RUNNING
1:2:2 successfully in state RUNNING
1:2:3 successfully in state RUNNING
1:2:4 successfully in state RUNNING
[many more lines like this]

I tried again and the second time it didn't get past loading:

Progress Loading application data onto the machine
|0                           50%                         100%|
 ===Retry due to SCPResult.RC_P2P_TIMEOUT
=Retry due to SCPResult.RC_P2P_TIMEOUT

[many more TIMEOUT messages]

=Traceback (most recent call last):
  File "va_network_scaled_AER.py", line 531, in <module>
    Frontend.run(runtime)    # Simulation time
  File "/usr/local/lib/python2.7/dist-packages/spynnaker/pyNN/__init__.py", line 188, in run
    _spinnaker.run(run_time)
  File "/usr/local/lib/python2.7/dist-packages/spynnaker/pyNN/spinnaker.py", line 352, in run
    app_data_folder=self._app_data_runtime_folder)
  File "/usr/local/lib/python2.7/dist-packages/spinn_front_end_common/interface/front_end_common_interface_functions.py", line 443, in _load_application_data
    application_data_file_reader, memory_written)
  File "/usr/local/lib/python2.7/dist-packages/spinnman/transceiver.py", line 1410, in write_memory
    callback.get_response()
  File "/usr/local/lib/python2.7/dist-packages/spinnman/_threads/_scp_message_interface.py", line 66, in run
    timeout=self._timeout, connection=self._connection)
  File "/usr/local/lib/python2.7/dist-packages/spinnman/transceiver.py", line 514, in _send_message
    message, response_required, timeout)
  File "/usr/local/lib/python2.7/dist-packages/spinnman/connections/listeners/_connection_queue.py", line 100, in send_message
    return callback.wait_for_receive()
  File "/usr/local/lib/python2.7/dist-packages/spinnman/connections/listeners/_message_callback.py", line 125, in wait_for_receive
    self._message_receive_traceback)
spinnman.exceptions.SpinnmanUnexpectedResponseCodeException: Unexpected response RC_P2P_NOREPLY while performing operation WriteMemory using command CMD_WRITE

**Comment by rowleya** [comment]
This may be related to #90 - further testing is required once this change has been integrated.

**Comment by alan-stokes** [comment]
assumed that this has cleared itself. Can be reopened if this is not the case

**Comment by svadams** [comment]
Not as far as I'm concerned! There was no fix indicated on ticket so I didn't see any point in trying again.

If something has been fixed for next release I will upgrade and try again, so can we have the ticket open again please?

Ta
Sam

Sent from my HTC


----- Reply message -----

**Comment by alan-stokes** [comment]
hi sam, so the issue with the sdram has been fixed, and is in the arbitirary release. So once that is offically rolled out, maybe you can try it and see if this issue goes away.

**Comment by alan-stokes** [comment]
Having tested this with Sam and the arbitiary release, the issue disappeared. therefore closing the issue.
